### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by kilbith** [Ferk/Dungeontest#2]
Hello @Ferk,

You're using some xdecor's code inside your `dungeon_decor` mod.

You have licensed the Lua code under LGPL, whilst the xdecor code is GPL. This is not allowed to re-license GPL to LGPL.

Please switch to GPLv3 (including a copy of the GPL text) as soon as possible.

Regards,
kilbith

**Comment by Ferk** [comment]
Hi kilbith, sorry for the delay addressing the matter, I was out for chinese new year.
I've changed the README.org and added a LICENSE file as requested, using the GPLv3
